name: Deploy Grafana Dashboard

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        choco install jq

    - name: Deploy Grafana Dashboard
      env:
        GRAFANA_URL: ${{ secrets.GRAFANA_URL }}
        GRAFANA_API_KEY: ${{ secrets.GRAFANA_API_KEY }}
      run: |
        $DASHBOARD_JSON = Get-Content "Grafana-Dashboards/App_Performance_Data-1716450378833.json" -Raw
        Invoke-RestMethod -Uri "${env:GRAFANA_URL}/api/dashboards/db" -Method Post -Headers @{ "Content-Type" = "application/json"; "Authorization" = "Bearer ${env:GRAFANA_API_KEY}" } -Body $DASHBOARD_JSON
